# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mnist.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmnist.proto\x12\rmnist_service\"\"\n\x0b\x44\x61taRequest\x12\x13\n\x0bsample_size\x18\x01 \x01(\x03\"&\n\x06Sample\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05label\x18\x02 \x01(\x03\x32[\n\x0cMnistService\x12K\n\x12GetTrainingSamples\x12\x1a.mnist_service.DataRequest\x1a\x15.mnist_service.Sample\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mnist_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DATAREQUEST']._serialized_start=30
  _globals['_DATAREQUEST']._serialized_end=64
  _globals['_SAMPLE']._serialized_start=66
  _globals['_SAMPLE']._serialized_end=104
  _globals['_MNISTSERVICE']._serialized_start=106
  _globals['_MNISTSERVICE']._serialized_end=197
# @@protoc_insertion_point(module_scope)
